system:
    default:
        image_variations:
            nglayouts_app_preview:
                reference: original
                filters:
                    - { name: thumbnail, params: { size: [160, 90], mode: outbound } }
                    - { name: strip }
