services:
    netgen_block_manager.layout.resolver.condition_type.ez_site_access:
        class: Netgen\BlockManager\Ez\Layout\Resolver\ConditionType\SiteAccess
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_block_manager.layout.resolver.condition_type.ez_site_access_group:
        class: Netgen\BlockManager\Ez\Layout\Resolver\ConditionType\SiteAccessGroup
        public: false
        arguments:
            - "%ezpublish.siteaccess.groups_by_siteaccess%"
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_block_manager.layout.resolver.condition_type.ez_content_type:
        class: Netgen\BlockManager\Ez\Layout\Resolver\ConditionType\ContentType
        public: false
        arguments:
            - "@netgen_block_manager.ezpublish.content_extractor"
            - "@ezpublish.api.service.content_type"
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }
