services:
    netgen_block_manager.layout.resolver.condition_type.ez_site_access:
        class: Netgen\BlockManager\Ez\Layout\Resolver\ConditionType\SiteAccess
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type, priority: 21 }

    netgen_block_manager.layout.resolver.condition_type.ez_content_type:
        class: Netgen\BlockManager\Ez\Layout\Resolver\ConditionType\ContentType
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type, priority: 20 }
