services:
    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.children:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\Children
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_children }

    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.subtree:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\Subtree
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_subtree }

    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.location:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\Location
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_location }

    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.content:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\Content
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_content }

    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.semantic_path_info:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\SemanticPathInfo
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_semantic_path_info }

    netgen_layouts.ezplatform.layout_resolver.target_type.form_mapper.semantic_path_info_prefix:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\TargetType\Mapper\SemanticPathInfoPrefix
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: ez_semantic_path_info_prefix }

    netgen_layouts.ezplatform.layout_resolver.condition_type.form_mapper.site_access:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\ConditionType\Mapper\SiteAccess
        arguments:
            - "%ezpublish.siteaccess.list%"
        tags:
            - { name: netgen_layouts.condition_type.form_mapper, condition_type: ez_site_access }

    netgen_layouts.ezplatform.layout_resolver.condition_type.form_mapper.site_access_group:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\ConditionType\Mapper\SiteAccessGroup
        arguments:
            - "%ezpublish.siteaccess.groups%"
        tags:
            - { name: netgen_layouts.condition_type.form_mapper, condition_type: ez_site_access_group }

    netgen_layouts.ezplatform.layout_resolver.condition_type.form_mapper.content_type:
        class: Netgen\Layouts\Ez\Layout\Resolver\Form\ConditionType\Mapper\ContentType
        tags:
            - { name: netgen_layouts.condition_type.form_mapper, condition_type: ez_content_type }
