services:
    netgen_block_manager.layout.resolver.form.target_type.mapper.ezchildren:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\Children
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ezchildren }

    netgen_block_manager.layout.resolver.form.target_type.mapper.ezsubtree:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\Subtree
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ezsubtree }

    netgen_block_manager.layout.resolver.form.target_type.mapper.ezlocation:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\Location
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ezlocation }

    netgen_block_manager.layout.resolver.form.target_type.mapper.ezcontent:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\Content
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ezcontent }

    netgen_block_manager.layout.resolver.form.target_type.mapper.ez_semantic_path_info:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\SemanticPathInfo
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ez_semantic_path_info }

    netgen_block_manager.layout.resolver.form.target_type.mapper.ez_semantic_path_info_prefix:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\TargetType\Mapper\SemanticPathInfoPrefix
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: ez_semantic_path_info_prefix }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.ez_site_access:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\ConditionType\Mapper\SiteAccess
        arguments:
            - "%ezpublish.siteaccess.list%"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: ez_site_access }

    netgen_block_manager.layout.resolver.form.condition_type.mapper.ez_content_type:
        class: Netgen\BlockManager\Ez\Layout\Resolver\Form\ConditionType\Mapper\ContentType
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: ez_content_type }
