services:
    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.location:
        class: Netgen\Layouts\Ibexa\Layout\Resolver\TargetHandler\Doctrine\Location
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_location }

    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.content:
        class: Netgen\Layouts\Ibexa\Layout\Resolver\TargetHandler\Doctrine\Location
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_content }

    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.children:
        class: Netgen\Layouts\Ibexa\Layout\Resolver\TargetHandler\Doctrine\Location
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_children }

    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.subtree:
        class: Netgen\Layouts\Ibexa\Layout\Resolver\TargetHandler\Doctrine\Subtree
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_subtree }

    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.semantic_path_info:
        class: Netgen\Layouts\Layout\Resolver\TargetHandler\Doctrine\Route
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_semantic_path_info }

    netgen_layouts.ibexa.layout_resolver.target_handler.doctrine.semantic_path_info_prefix:
        class: Netgen\Layouts\Layout\Resolver\TargetHandler\Doctrine\RoutePrefix
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: ibexa_semantic_path_info_prefix }
