services:
    netgen_layouts.ezplatform.layout_resolver.target_type.location:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\Location
        arguments:
            - "@netgen_layouts.ezplatform.content_extractor"
            - "@netgen_layouts.ezplatform.utils.remote_id_converter"
        tags:
            - { name: netgen_layouts.target_type, priority: 140 }

    netgen_layouts.ezplatform.layout_resolver.target_type.content:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\Content
        arguments:
            - "@netgen_layouts.ezplatform.content_extractor"
            - "@netgen_layouts.ezplatform.utils.remote_id_converter"
        tags:
            - { name: netgen_layouts.target_type, priority: 150 }

    netgen_layouts.ezplatform.layout_resolver.target_type.children:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\Children
        arguments:
            - "@netgen_layouts.ezplatform.content_extractor"
            - "@netgen_layouts.ezplatform.utils.remote_id_converter"
        tags:
            - { name: netgen_layouts.target_type, priority: 120 }

    netgen_layouts.ezplatform.layout_resolver.target_type.subtree:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\Subtree
        arguments:
            - "@netgen_layouts.ezplatform.content_extractor"
            - "@netgen_layouts.ezplatform.utils.remote_id_converter"
        tags:
            - { name: netgen_layouts.target_type, priority: 130 }

    netgen_layouts.ezplatform.layout_resolver.target_type.semantic_path_info:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\SemanticPathInfo
        tags:
            - { name: netgen_layouts.target_type, priority: 110 }

    netgen_layouts.ezplatform.layout_resolver.target_type.semantic_path_info_prefix:
        class: Netgen\Layouts\Ez\Layout\Resolver\TargetType\SemanticPathInfoPrefix
        tags:
            - { name: netgen_layouts.target_type, priority: 100 }
