parameters:
    netgen_block_manager.layout.resolver.target_type.ezlocation.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\Location
    netgen_block_manager.layout.resolver.target_type.ezcontent.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\Content
    netgen_block_manager.layout.resolver.target_type.ezchildren.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\Children
    netgen_block_manager.layout.resolver.target_type.ezsubtree.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\Subtree
    netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\SemanticPathInfo
    netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info_prefix.class: Netgen\BlockManager\Ez\Layout\Resolver\TargetType\SemanticPathInfoPrefix

services:
    netgen_block_manager.layout.resolver.target_type.ezlocation:
        class: "%netgen_block_manager.layout.resolver.target_type.ezlocation.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 24 }

    netgen_block_manager.layout.resolver.target_type.ezcontent:
        class: "%netgen_block_manager.layout.resolver.target_type.ezcontent.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 25 }

    netgen_block_manager.layout.resolver.target_type.ezchildren:
        class: "%netgen_block_manager.layout.resolver.target_type.ezchildren.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 22 }

    netgen_block_manager.layout.resolver.target_type.ezsubtree:
        class: "%netgen_block_manager.layout.resolver.target_type.ezsubtree.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 23 }

    netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info:
        class: "%netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 20 }

    netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info_prefix:
        class: "%netgen_block_manager.layout.resolver.target_type.ez_semantic_path_info_prefix.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type, priority: 21 }
