services:
    netgen_layouts.ezplatform.parameters.parameter_type.tags:
        class: Netgen\Layouts\Ez\Parameters\ParameterType\TagsType
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ezplatform.parameters.form_mapper.tags:
        class: Netgen\Layouts\Ez\Parameters\Form\Mapper\TagsMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ez_tags }

    netgen_layouts.ezplatform.validator.tags:
        class: Netgen\Layouts\Ez\Validator\TagValidator
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_ez_tags }
