parameters:
    netgen_block_manager.parameters.parameter_handler.eztags.class: Netgen\BlockManager\Ez\Parameters\FormMapper\ParameterHandler\Tags
    netgen_block_manager.validator.eztag.class: Netgen\BlockManager\Ez\Validator\TagValidator

services:
    netgen_block_manager.parameters.parameter_handler.eztags:
        class: "%netgen_block_manager.parameters.parameter_handler.eztags.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_handler, type: eztags }

    netgen_block_manager.validator.eztag:
        class: "%netgen_block_manager.validator.eztag.class%"
        arguments:
            - "@ezpublish.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_eztag }
