parameters:
    netgen_block_manager.parameters.parameter_type.eztags.class: Netgen\BlockManager\Ez\Parameters\ParameterType\TagsType
    netgen_block_manager.parameters.form.mapper.eztags.class: Netgen\BlockManager\Ez\Parameters\Form\Mapper\TagsMapper
    netgen_block_manager.validator.eztag.class: Netgen\BlockManager\Ez\Validator\TagValidator

services:
    netgen_block_manager.parameters.parameter_type.eztags:
        class: "%netgen_block_manager.parameters.parameter_type.eztags.class%"
        tags:
            - { name: netgen_block_manager.parameters.parameter_type }

    netgen_block_manager.parameters.form.mapper.eztags:
        class: "%netgen_block_manager.parameters.form.mapper.eztags.class%"
        tags:
            - { name: netgen_block_manager.parameters.form.mapper, type: eztags }

    netgen_block_manager.validator.eztag:
        class: "%netgen_block_manager.validator.eztag.class%"
        arguments:
            - "@ezpublish.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_eztag }
