dist: trusty
sudo: false

language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"

matrix:
  include:
    -
      php: 7.1
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0" DEPS="low"
    -
      php: 7.2
      env: RUN_PHPSTAN="yes"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer require --no-update symfony/symfony:$SYMFONY_VERSION ; fi

  # PHPStan and eZ Platform Admin UI cannot be installed on Symfony 2.8
  - if [ "$SYMFONY_VERSION" = "~2.8.0" ] ; then composer remove --dev --no-update phpstan/phpstan phpstan/phpstan-phpunit ezsystems/ezplatform-admin-ui ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi

notifications:
  email: false
  slack:
    secure: j2rUMFQitNUT9oyeWHqhBtVwCs7ogGszxMtCRGPpEnc/d5z2L0ObKlxgTRrYCFETIOya+pzqrTeYIlmpcQ4c6cRYpbiyg1Zs5bQtVwbVWye3efezP38JFQUoCos0Uu5bgO2LTdyq7cyn6vqksA3Fsr112w83NtUgfbrQMCTfj1pLBAgekd0XwtTC1cFU9qcgifKGFtsHrJq55vOKf67cQPEts0+TpwUJHg6pLchl7NHV+5CUVSHx3pYzHwF23lLmiVrCWn4tcPFAfAvADiSv/vUeSz1YUftd/iPLQW4wSGWP8y43MnleZ0uYLrenaeBKehigMyYxNR7WJfP65/je3+WPgvsD/h4ncdTkG0aobLxYSn3fCCvj6+rHjEIROZVl6B3K3GLfzaNUCj+UWezNE4lcDISUlAxodFlnLdlrqcy6vGnDJEmpEF4sahPlrU+zeozwwRDxRB1hU1+c5Q4NcW3cw6lZsNQIKFYzpsXgzkwYMiqQSI2GUOiNSSBoDbxlQG7CWw7Mnd9W7WRWRBAYz6+Fu1m0Y2sgSV0rktGlV6GX1bxwiXyBcHSicYNEiE2tgCikUr3zUt+P7nWB3gpPerFHJ8/+8fsRzi9pixyGvXTmZkzFpbFjEDv3Iyi7q2Dnw/fYHAXMeWbopen84Z56k2aHWUKRtOPDDU+laLocQlM=
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
