parameters:
    netgen_layouts.ezplatform.data_collector.site_access_group_name: 'admin_group'
    netgen_layouts.ezplatform.data_collector.default_site_access_name: 'admin'

services:
    netgen_layouts.ezplatform.debug.data_collector.layout_url_generator:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Debug\DataCollector\LayoutUrlGenerator
        decorates: netgen_layouts.debug.data_collector.layout_url_generator
        arguments:
            - "@netgen_layouts.ezplatform.debug.data_collector.layout_url_generator.inner"
            - "%ezpublish.siteaccess.groups%"
            - "%netgen_layouts.ezplatform.data_collector.site_access_group_name%"
            - "%netgen_layouts.ezplatform.data_collector.default_site_access_name%"
