services:
    netgen_layouts.ezplatform.debug.data_collector.layout_url_generator:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Debug\DataCollector\LayoutUrlGenerator
        decorates: netgen_layouts.debug.data_collector.layout_url_generator
        arguments:
            - "@.inner"
            - "%ezpublish.siteaccess.groups%"
