block_definitions:
    ezcontent_field:
        forms:
            full:
                type: ~
        view_types:
            ezcontent_field:
                name: 'eZ content field'
                item_view_types:
                    standard:
                        name: 'Standard'
