parameters:
    netgen_block_manager.default.block_view: []
    netgen_block_manager.default.layout_view: []
    netgen_block_manager.default.blocks: []
    netgen_block_manager.default.layouts: []
    netgen_block_manager.default.block_groups: []
