parameters:
    netgen_block_manager.default.block_view: []
    netgen_block_manager.default.layout_view: []
    netgen_block_manager.default.query_view: []
    netgen_block_manager.default.pagelayout: 'NetgenBlockManagerBundle::pagelayout_empty.html.twig'
