services:
    netgen_block_manager.serializer.block:
        class: %netgen_block_manager.serializer.block.class%
        arguments:
            - $blocks;netgen_block_manager$
        tags:
            - { name: jms_serializer.subscribing_handler }

    netgen_block_manager.serializer.layout:
        class: %netgen_block_manager.serializer.layout.class%
        arguments:
            - $layouts;netgen_block_manager$
        tags:
            - { name: jms_serializer.subscribing_handler }
