parameters:
    netgen_block_manager.collection.query_type.ezcontent_search.class: Netgen\Bundle\EzPublishBlockManagerBundle\Collection\QueryType\EzContentSearch

services:
    netgen_block_manager.collection.query_type.ezcontent_search:
        class: "%netgen_block_manager.collection.query_type.ezcontent_search.class%"
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.search"
        tags:
            - { name: netgen_block_manager.collection.query_type }
