parameters:
    netgen_block_manager.collection.value_converter.ezcontent.class: Netgen\Bundle\EzPublishBlockManagerBundle\Collection\ValueConverter\EzContentValueConverter
    netgen_block_manager.collection.value_converter.ezlocation.class: Netgen\Bundle\EzPublishBlockManagerBundle\Collection\ValueConverter\EzLocationValueConverter

services:
    netgen_block_manager.collection.value_converter.ezcontent:
        class: "%netgen_block_manager.collection.value_converter.ezcontent.class%"
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_block_manager.collection.value_converter }

    netgen_block_manager.collection.value_converter.ezlocation:
        class: "%netgen_block_manager.collection.value_converter.ezlocation.class%"
        arguments:
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_block_manager.collection.value_converter }
