services:
    netgen_layouts.ezplatform.block.block_definition_handler.content_field:
        class: Netgen\Layouts\Ez\Block\BlockDefinition\Handler\ContentFieldHandler
        arguments:
            - "@netgen_layouts.ezplatform.content_provider"
        tags:
            - { name: netgen_layouts.block_definition_handler, identifier: ezcontent_field }
