services:
    netgen_layouts.ibexa.block.block_definition_handler.content_field:
        class: Netgen\Layouts\Ibexa\Block\BlockDefinition\Handler\ContentFieldHandler
        arguments:
            - "@netgen_layouts.ibexa.content_provider"
        tags:
            - { name: netgen_layouts.block_definition_handler, identifier: ibexa_content_field }
