parameters:
    netgen_block_manager.block.block_definition.handler.ezcontent_field.class: Netgen\BlockManager\Ez\Block\BlockDefinition\Handler\ContentFieldHandler

    netgen_block_manager.block.block_definition.handler.title.value_types: ['ezlocation']
    netgen_block_manager.block.block_definition.handler.link.value_types: ['ezlocation']

services:
    netgen_block_manager.block.block_definition.handler.ezcontent_field:
        class: "%netgen_block_manager.block.block_definition.handler.ezcontent_field.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: ezcontent_field }
