parameters:
    netgen_block_manager.block.block_definition.handler.ezcontent_field.class: Netgen\BlockManager\Ez\Block\BlockDefinition\Handler\ContentFieldHandler

services:
    netgen_block_manager.block.block_definition.handler.ezcontent_field:
        class: "%netgen_block_manager.block.block_definition.handler.ezcontent_field.class%"
        arguments:
            - "@netgen_block_manager.ezpublish.content_provider"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: ezcontent_field }
