services:
    netgen_layouts.ibexa.configuration.config_resolver:
        class: Netgen\Bundle\LayoutsIbexaBundle\Configuration\ConfigResolverConfiguration
        arguments:
            - "@ibexa.config.resolver"
            - "@netgen_layouts.configuration.container"
        lazy: true

    netgen_layouts.configuration:
        alias: netgen_layouts.ibexa.configuration.config_resolver
        public: true
