services:
    netgen_layouts.ezplatform.configuration.config_resolver:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Configuration\ConfigResolverConfiguration
        arguments:
            - "@ezpublish.config.resolver"
            - "@netgen_block_manager.configuration.container"
        lazy: true

    netgen_block_manager.configuration:
        alias: netgen_layouts.ezplatform.configuration.config_resolver
        public: true
