services:
    netgen_block_manager.configuration.config_resolver:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Configuration\ConfigResolverConfiguration
        public: false
        arguments:
            - "@ezpublish.config.resolver"
            - "@netgen_block_manager.configuration.container"
        lazy: true

    netgen_block_manager.configuration:
        alias: netgen_block_manager.configuration.config_resolver
