services:
    netgen_layouts.ezplatform.context.provider:
        class: Netgen\Layouts\Ez\Context\ContextProvider
        arguments:
            - "@request_stack"
        tags:
            - { name: netgen_block_manager.context.provider }
