services:
    netgen_block_manager.context.provider.ezpublish:
        class: Netgen\BlockManager\Ez\Context\ContextProvider
        public: false
        arguments:
            - "@request_stack"
        tags:
            - { name: netgen_block_manager.context.provider }
