services:
    netgen_layouts.ezplatform.context.provider:
        class: Netgen\Layouts\Ez\Context\ContextProvider
        arguments:
            - "@request_stack"
        tags:
            - { name: netgen_layouts.context_provider }
