services:
    netgen_block_manager.context.provider.ezplatform:
        class: Netgen\BlockManager\Ez\Context\ContextProvider
        arguments:
            - "@request_stack"
        tags:
            - { name: netgen_block_manager.context.provider }
