services:
    netgen_block_manager.ezpublish.content_extractor:
        alias: netgen_block_manager.ezpublish.content_extractor.ez5_request
        public: false

    netgen_block_manager.ezpublish.content_extractor.ez5_request:
        class: Netgen\BlockManager\Ez\ContentProvider\Ez5RequestContentExtractor
        public: false
        deprecated: ~
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.location"
