services:
    netgen_block_manager.form.ez_content_type:
        class: Netgen\BlockManager\Ez\Form\ContentTypeType
        # public: false
        arguments:
            - "@ezpublish.api.service.content_type"
        tags:
            - { name: form.type }

    netgen_block_manager.form.ez_section:
        class: Netgen\BlockManager\Ez\Form\SectionType
        # public: false
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: form.type }

    netgen_block_manager.form.ez_object_state:
        class: Netgen\BlockManager\Ez\Form\ObjectStateType
        # public: false
        arguments:
            - "@ezpublish.api.service.object_state"
        tags:
            - { name: form.type }
