services:
    netgen_layouts.ibexa.http_cache.repository_prefix_decorator_client:
        class: Netgen\Layouts\Ibexa\HttpCache\RepositoryPrefixDecorator
        decorates: netgen_layouts.http_cache.client
        arguments:
            - "@netgen_layouts.ibexa.http_cache.repository_prefix_decorator_client.inner"
            - "@Ibexa\\HttpCache\\RepositoryTagPrefix"

    netgen_layouts.ibexa.http_cache.varnish.host_header_provider:
        class: Netgen\Layouts\Ibexa\HttpCache\Varnish\HostHeaderProvider
        arguments:
            - "@ibexa.config.resolver"

    netgen_layouts.ibexa.http_cache.client.local:
        class: Netgen\Layouts\Ibexa\HttpCache\LocalClient
        arguments:
            - "@Toflar\\Psr6HttpCacheStore\\Psr6Store"
