services:
    netgen_layouts.ezplatform.item.value_converter.location:
        class: Netgen\Layouts\Ez\Item\ValueConverter\LocationValueConverter
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.ezplatform.item.value_converter.content:
        class: Netgen\Layouts\Ez\Item\ValueConverter\ContentValueConverter
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.content"
        tags:
            - { name: netgen_layouts.cms_value_converter }

    netgen_layouts.ezplatform.item.value_loader.location:
        class: Netgen\Layouts\Ez\Item\ValueLoader\LocationValueLoader
        arguments:
            - "@ezpublish.api.service.location"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: ezlocation }

    netgen_layouts.ezplatform.item.value_loader.content:
        class: Netgen\Layouts\Ez\Item\ValueLoader\ContentValueLoader
        arguments:
            - "@ezpublish.api.service.content"
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: ezcontent }

    netgen_layouts.ezplatform.item.value_url_generator.location:
        class: Netgen\Layouts\Ez\Item\ValueUrlGenerator\LocationValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: ezlocation }

    netgen_layouts.ezplatform.item.value_url_generator.content:
        class: Netgen\Layouts\Ez\Item\ValueUrlGenerator\ContentValueUrlGenerator
        arguments:
            - "@router"
        tags:
            - { name: netgen_layouts.cms_value_url_generator, value_type: ezcontent }
