services:
    netgen_layouts.ibexa.parameters.value_object_provider.location:
        class: Netgen\Layouts\Ibexa\Parameters\ValueObjectProvider\LocationProvider
        arguments:
            - "@ibexa.api.repository"
            - "@netgen_layouts.error.handler"

    netgen_layouts.ibexa.parameters.parameter_type.location:
        class: Netgen\Layouts\Ibexa\Parameters\ParameterType\LocationType
        arguments:
            - "@ibexa.api.repository"
            - "@netgen_layouts.ibexa.parameters.value_object_provider.location"
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ibexa.parameters.value_object_provider.content:
        class: Netgen\Layouts\Ibexa\Parameters\ValueObjectProvider\ContentProvider
        arguments:
            - "@ibexa.api.repository"
            - "@netgen_layouts.error.handler"

    netgen_layouts.ibexa.parameters.parameter_type.content:
        class: Netgen\Layouts\Ibexa\Parameters\ParameterType\ContentType
        arguments:
            - "@ibexa.api.repository"
            - "@netgen_layouts.ibexa.parameters.value_object_provider.content"
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ibexa.parameters.parameter_type.content_type:
        class: Netgen\Layouts\Ibexa\Parameters\ParameterType\ContentTypeType
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ibexa.parameters.parameter_type.section:
        class: Netgen\Layouts\Ibexa\Parameters\ParameterType\SectionType
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ibexa.parameters.parameter_type.object_state:
        class: Netgen\Layouts\Ibexa\Parameters\ParameterType\ObjectStateType
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.ibexa.parameters.form_mapper.location:
        class: Netgen\Layouts\Ibexa\Parameters\Form\Mapper\LocationMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ibexa_location }

    netgen_layouts.ibexa.parameters.form_mapper.content:
        class: Netgen\Layouts\Ibexa\Parameters\Form\Mapper\ContentMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ibexa_content }

    netgen_layouts.ibexa.parameters.form_mapper.content_type:
        class: Netgen\Layouts\Ibexa\Parameters\Form\Mapper\ContentTypeMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ibexa_content_type }

    netgen_layouts.ibexa.parameters.form_mapper.section:
        class: Netgen\Layouts\Ibexa\Parameters\Form\Mapper\SectionMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ibexa_section }

    netgen_layouts.ibexa.parameters.form_mapper.object_state:
        class: Netgen\Layouts\Ibexa\Parameters\Form\Mapper\ObjectStateMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: ibexa_object_state }
