services:
    # Alias to eZ Platform search service, allowing for replacement
    # of search service with other implementations system wide

    netgen_layouts.ezplatform.search_service:
        alias: ezpublish.api.service.search

    netgen_layouts.ezplatform.content_provider:
        class: Netgen\Layouts\Ez\ContentProvider\ContentProvider
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_layouts.context"

    netgen_layouts.ezplatform.content_extractor:
        alias: netgen_layouts.ezplatform.content_extractor.request

    netgen_layouts.ezplatform.content_extractor.request:
        class: Netgen\Layouts\Ez\ContentProvider\RequestContentExtractor

    netgen_layouts.ezplatform.security.role_hierarchy:
        class: Netgen\Layouts\Ez\Security\Role\RoleHierarchy
        arguments:
            - "%security.role_hierarchy.roles%"

    netgen_layouts.ezplatform.security.repository_access_voter:
        class: Netgen\Layouts\Ez\Security\Authorization\Voter\RepositoryAccessVoter
        arguments:
            - "@netgen_layouts.ezplatform.security.role_hierarchy"
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter, priority: 0 }

    netgen_layouts.ezplatform.utils.remote_id_converter:
        class: Netgen\Layouts\Ez\Utils\RemoteIdConverter
        arguments:
            - "@ezpublish.api.repository"
