services:
    # Alias to eZ Publish search service, allowing for replacement
    # of search service with other implementations system wide

    netgen_block_manager.ezpublish.search_service:
        alias: ezpublish.api.service.search

    netgen_block_manager.ezpublish.content_provider:
        class: Netgen\BlockManager\Ez\ContentProvider\ContentProvider
        public: true
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.content"
            - "@netgen_block_manager.context"

    netgen_block_manager.ezpublish.content_extractor:
        alias: netgen_block_manager.ezpublish.content_extractor.request
        public: false

    netgen_block_manager.ezpublish.content_extractor.request:
        class: Netgen\BlockManager\Ez\ContentProvider\RequestContentExtractor
        public: false

    netgen_block_manager.ezpublish.content_extractor.ez5_request:
        class: Netgen\BlockManager\Ez\ContentProvider\Ez5RequestContentExtractor
        public: false
        deprecated: ~
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.location"

    netgen_block_manager.ezpublish.security.role_hierarchy:
        class: Netgen\BlockManager\Ez\Security\Role\RoleHierarchy
        public: false
        arguments:
            - "%security.role_hierarchy.roles%"

    netgen_block_manager.ezpublish.security.repository_access_voter:
        class: Netgen\BlockManager\Ez\Security\Authorization\Voter\RepositoryAccessVoter
        public: false
        arguments:
            - "@netgen_block_manager.ezpublish.security.role_hierarchy"
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter }
