services:
    netgen_block_manager.ezpublish.content_provider:
        alias: netgen_block_manager.ezpublish.content_provider.request

    netgen_block_manager.ezpublish.content_provider.request:
        class: Netgen\BlockManager\Ez\ContentProvider\RequestContentProvider
        calls:
            - [setRequestStack, ["@request_stack"]]

    netgen_block_manager.ezpublish.content_provider.ez5_request:
        class: Netgen\BlockManager\Ez\ContentProvider\Ez5RequestContentProvider
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.location"
        calls:
            - [setRequestStack, ["@request_stack"]]

    netgen_block_manager.ezpublish.security.repository_access_voter:
        class: Netgen\BlockManager\Ez\Security\Authorization\Voter\RepositoryAccessVoter
        public: false
        arguments:
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter }
