services:
    netgen_block_manager.ezpublish.content_provider:
        class: Netgen\BlockManager\Ez\ContentProvider\ContentProvider
        arguments:
            - "@netgen_block_manager.ezpublish.content_extractor"
            - "@request_stack"

    netgen_block_manager.ezpublish.content_extractor:
        alias: netgen_block_manager.ezpublish.content_extractor.request

    netgen_block_manager.ezpublish.content_extractor.request:
        class: Netgen\BlockManager\Ez\ContentProvider\RequestContentExtractor

    netgen_block_manager.ezpublish.content_extractor.ez5_request:
        class: Netgen\BlockManager\Ez\ContentProvider\Ez5RequestContentExtractor
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.location"

    netgen_block_manager.ezpublish.security.role_hierarchy:
        class: Netgen\BlockManager\Ez\Security\Role\RoleHierarchy
        public: false
        arguments:
            - "%security.role_hierarchy.roles%"

    netgen_block_manager.ezpublish.security.repository_access_voter:
        class: Netgen\BlockManager\Ez\Security\Authorization\Voter\RepositoryAccessVoter
        public: false
        arguments:
            - "@netgen_block_manager.ezpublish.security.role_hierarchy"
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter }
