services:
    # Alias to eZ Platform search service, allowing for replacement
    # of search service with other implementations system wide

    netgen_block_manager.ezpublish.search_service:
        alias: ezpublish.api.service.search

    netgen_block_manager.ezpublish.content_provider:
        class: Netgen\BlockManager\Ez\ContentProvider\ContentProvider
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_block_manager.context"

    netgen_block_manager.ezpublish.content_extractor:
        alias: netgen_block_manager.ezpublish.content_extractor.request

    netgen_block_manager.ezpublish.content_extractor.request:
        class: Netgen\BlockManager\Ez\ContentProvider\RequestContentExtractor

    netgen_block_manager.ezpublish.security.role_hierarchy:
        class: Netgen\BlockManager\Ez\Security\Role\RoleHierarchy
        arguments:
            - "%security.role_hierarchy.roles%"

    netgen_block_manager.ezpublish.security.repository_access_voter:
        class: Netgen\BlockManager\Ez\Security\Authorization\Voter\RepositoryAccessVoter
        arguments:
            - "@netgen_block_manager.ezpublish.security.role_hierarchy"
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter, priority: 0 }
