services:
    netgen_block_manager.templating.pagelayout_resolver.ezpublish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\PageLayoutResolver
        public: false
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver.default"
            - "@ezpublish.config.resolver"
            - "@request_stack"
            - "%ezpublish.content_view.viewbase_layout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.ezpublish
        public: false

    netgen_block_manager.templating.twig.extension.ez_publish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Extension\EzPublishExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.ez_publish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Runtime\EzPublishRuntime
        # public: false
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: twig.runtime }
