services:
    netgen_block_manager.templating.pagelayout_resolver.ezplatform:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Templating\PageLayoutResolver
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver.default"
            - "@ezpublish.config.resolver"
            - "@request_stack"
            - "%ezpublish.content_view.viewbase_layout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.ezplatform

    netgen_block_manager.templating.twig.extension.ez_platform:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Templating\Twig\Extension\EzPlatformExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.ez_platform:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Templating\Twig\Runtime\EzPlatformRuntime
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: twig.runtime }
