services:
    netgen_block_manager.templating.pagelayout_resolver.ezpublish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\PageLayoutResolver
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver.default"
            - "@ezpublish.config.resolver"
            - "@request_stack"
            - "%ezpublish.content_view.viewbase_layout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.ezpublish

    netgen_block_manager.templating.twig.extension.ez_publish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Extension\EzPublishExtension
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.ez_publish.loader:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Runtime\Loader\EzPublishRuntimeLoader
        deprecated: ~
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: netgen_block_manager.twig.runtime_loader }

    netgen_block_manager.templating.twig.runtime.ez_publish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Runtime\EzPublishRuntime
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: twig.runtime }
