services:
    netgen_layouts.ibexa.templating.pagelayout_resolver:
        class: Netgen\Bundle\LayoutsIbexaBundle\Templating\PageLayoutResolver
        arguments:
            - "@netgen_layouts.templating.pagelayout_resolver.default"
            - "@ibexa.config.resolver"
            - "@request_stack"
            - "%ibexa.content_view.viewbase_layout%"

    netgen_layouts.templating.pagelayout_resolver:
        alias: netgen_layouts.ibexa.templating.pagelayout_resolver

    netgen_layouts.ibexa.templating.twig.extension.ibexa:
        class: Netgen\Bundle\LayoutsIbexaBundle\Templating\Twig\Extension\IbexaExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.ibexa.templating.twig.runtime.ibexa:
        class: Netgen\Bundle\LayoutsIbexaBundle\Templating\Twig\Runtime\IbexaRuntime
        arguments:
            - "@ibexa.api.repository"
        tags:
            - { name: twig.runtime }
