services:
    netgen_block_manager.templating.pagelayout_resolver.ezpublish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\PageLayoutResolver
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver.default"
            - "@ezpublish.config.resolver"
            - "%ezpublish.content_view.viewbase_layout%"
        calls:
            - [setRequestStack, ["@request_stack"]]

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.ezpublish

    netgen_block_manager.templating.twig.extension.ez_publish:
        class: Netgen\Bundle\EzPublishBlockManagerBundle\Templating\Twig\Extension\EzPublishExtension
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
        tags:
            - { name: twig.extension }
