parameters:
    netgen_block_manager.validator.ezlocation.class: Netgen\BlockManager\Ez\Validator\LocationValidator
    netgen_block_manager.validator.ezcontent.class: Netgen\BlockManager\Ez\Validator\ContentValidator
    netgen_block_manager.validator.ez_site_access.class: Netgen\BlockManager\Ez\Validator\SiteAccessValidator
    netgen_block_manager.validator.ez_content_type.class: Netgen\BlockManager\Ez\Validator\ContentTypeValidator

services:
    netgen_block_manager.validator.ezlocation:
        class: "%netgen_block_manager.validator.ezlocation.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezlocation }

    netgen_block_manager.validator.ezcontent:
        class: "%netgen_block_manager.validator.ezcontent.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezcontent }

    netgen_block_manager.validator.ez_site_access:
        class: "%netgen_block_manager.validator.ez_site_access.class%"
        arguments:
            - "%ezpublish.siteaccess.list%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_site_access }


    netgen_block_manager.validator.ez_content_type:
        class: "%netgen_block_manager.validator.ez_content_type.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_content_type }
