services:
    netgen_block_manager.validator.ezlocation:
        class: Netgen\Layouts\Ez\Validator\LocationValidator
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezlocation }

    netgen_block_manager.validator.ezcontent:
        class: Netgen\Layouts\Ez\Validator\ContentValidator
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezcontent }

    netgen_block_manager.validator.ez_site_access:
        class: Netgen\Layouts\Ez\Validator\SiteAccessValidator
        arguments:
            - "%ezpublish.siteaccess.list%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_site_access }

    netgen_block_manager.validator.ez_site_access_group:
        class: Netgen\Layouts\Ez\Validator\SiteAccessGroupValidator
        arguments:
            - "%ezpublish.siteaccess.groups%"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_site_access_group }

    netgen_block_manager.validator.ez_content_type:
        class: Netgen\Layouts\Ez\Validator\ContentTypeValidator
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_content_type }

    netgen_block_manager.validator.ez_section:
        class: Netgen\Layouts\Ez\Validator\SectionValidator
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_section }

    netgen_block_manager.validator.ez_object_state:
        class: Netgen\Layouts\Ez\Validator\ObjectStateValidator
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ez_object_state }
