view:
    block_view:
        default:
            ezcontent_field:
                template: "NetgenEzPublishBlockManagerBundle:block:ezcontent_field.html.twig"
                match:
                    block\definition: ezcontent_field
