block_view:
    view:
        ezcontent_field:
            template: "NetgenEzPublishBlockManagerBundle:block/view:ezcontent_field.html.twig"
            match:
                block\definition: ezcontent_field
