form_view:
    view:
        query\full_edit\ezcontent_search:
            template: "NetgenEzPublishBlockManagerBundle:app/form/query/edit/full:ezcontent_search.html.twig"
            match:
                form\type: Netgen\BlockManager\Collection\Query\Form\FullEditType
                form\query\type: ezcontent_search
