rule_condition_view:
    view:
        ezsiteaccess:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/condition/view:ezsiteaccess.html.twig"
            match:
                rule_condition\type: ezsiteaccess
        ez_content_type:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/condition/view:ez_content_type.html.twig"
            match:
                rule_condition\type: ez_content_type
