rule_target_view:
    view:
        ezchildren:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ezchildren.html.twig"
            match:
                rule_target\type: ezchildren
        ezcontent:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ezcontent.html.twig"
            match:
                rule_target\type: ezcontent
        ezlocation:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ezlocation.html.twig"
            match:
                rule_target\type: ezlocation
        ezsubtree:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ezsubtree.html.twig"
            match:
                rule_target\type: ezsubtree
        ez_semantic_path_info:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ez_semantic_path_info.html.twig"
            match:
                rule_target\type: ez_semantic_path_info
        ez_semantic_path_info_prefix:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/target:ez_semantic_path_info_prefix.html.twig"
            match:
                rule_target\type: ez_semantic_path_info_prefix
