rule_condition_view:
    view:
        ez_site_access:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/condition/view:ez_site_access.html.twig"
            match:
                rule_condition\type: ez_site_access
        ez_content_type:
            template: "NetgenEzPublishBlockManagerBundle:admin/layout_resolver/condition/view:ez_content_type.html.twig"
            match:
                rule_condition\type: ez_content_type
