services:
    netgen_block_manager.view.template_resolver.block:
        class: %netgen_block_manager.view.template_resolver.class%
        lazy: true
        arguments:
            - []
            - $block_view;netgen_ez_publish_block_manager$
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\BlockViewInterface' }

    netgen_block_manager.view.template_resolver.layout:
        class: %netgen_block_manager.view.template_resolver.class%
        lazy: true
        arguments:
            - []
            - $layout_view;netgen_ez_publish_block_manager$
        tags:
            - { name: netgen_block_manager.view.template_resolver, type: 'Netgen\BlockManager\View\LayoutViewInterface' }
