services:
    netgen_block_manager.view.template_provider.block:
        class: %netgen_block_manager.view.template_provider.block.class%
        arguments:
            - $blocks;netgen_block_manager$
        tags:
            - { name: netgen_block_manager.view.template_provider, type: 'Netgen\BlockManager\View\BlockView' }

    netgen_block_manager.view.template_provider.layout:
        class: %netgen_block_manager.view.template_provider.layout.class%
        arguments:
            - $layouts;netgen_block_manager$
        tags:
            - { name: netgen_block_manager.view.template_provider, type: 'Netgen\BlockManager\View\LayoutView' }
