parameters:
    netgen_block_manager.configuration.config_resolver.class: Netgen\BlockManager\Ez\Configuration\ConfigResolverConfiguration

services:
    netgen_block_manager.configuration.config_resolver:
        class: "%netgen_block_manager.configuration.config_resolver.class%"
        arguments:
            - "@netgen_block_manager.configuration.container"
        calls:
            - [setConfigResolver, ["@ezpublish.config.resolver"]]
        lazy: true

    netgen_block_manager.configuration:
        alias: netgen_block_manager.configuration.config_resolver
