parameters:
    netgen_block_manager.event_listener.ez_pagelayout.class: Netgen\Bundle\EzPublishBlockManagerBundle\EventListener\PageLayoutListener
    netgen_block_manager.event_listener.block_view.ezcontent_field.class: Netgen\Bundle\EzPublishBlockManagerBundle\EventListener\BlockView\ContentFieldListener

services:
    netgen_block_manager.event_listener.ez_pagelayout:
        class: "%netgen_block_manager.event_listener.ez_pagelayout.class%"
        arguments:
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.templating.global_variable"
        tags:
            - { name: kernel.event_subscriber }

    netgen_block_manager.event_listener.block_view.ezcontent_field:
        class: "%netgen_block_manager.event_listener.block_view.ezcontent_field.class%"
        arguments:
            - "%netgen_block_manager.block_view.ezcontent_field_contexts%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: kernel.event_subscriber }
