parameters:
    netgen_block_manager.validator.ezlocation.class: Netgen\Bundle\EzPublishBlockManagerBundle\Validator\EzLocationValidator

services:
    netgen_block_manager.validator.ezlocation:
        class: "%netgen_block_manager.validator.ezlocation.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezlocation }
