parameters:
    netgen_block_manager.validator.ezlocation.class: Netgen\Bundle\EzPublishBlockManagerBundle\Validator\LocationValidator
    netgen_block_manager.validator.ezcontent.class: Netgen\Bundle\EzPublishBlockManagerBundle\Validator\ContentValidator

services:
    netgen_block_manager.validator.ezlocation:
        class: "%netgen_block_manager.validator.ezlocation.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezlocation }

    netgen_block_manager.validator.ezcontent:
        class: "%netgen_block_manager.validator.ezcontent.class%"
        arguments:
            - "@ezpublish.api.repository"
        tags:
            - { name: validator.constraint_validator, alias: ngbm_ezcontent }
