view:
    block_view:
        default:
            ibexa_content_field:
                template: "@nglayouts/block/ibexa_content_field.html.twig"
                match:
                    block\definition: ibexa_content_field
                    block\view_type: ibexa_content_field
        app:
            ibexa_content_field:
                template: "@NetgenLayoutsIbexa/app/block/ibexa_content_field.html.twig"
                match:
                    block\definition: ibexa_content_field
