view:
    item_view:
        default:
            ezcontent:
                template: "@ngbm/item/ezcontent.html.twig"
                match:
                    item\value_type: ezcontent
            ezlocation:
                template: "@ngbm/item/ezlocation.html.twig"
                match:
                    item\value_type: ezlocation
        ajax:
            ezcontent:
                template: "@ngbm/item/ezcontent.html.twig"
                match:
                    item\value_type: ezcontent
            ezlocation:
                template: "@ngbm/item/ezlocation.html.twig"
                match:
                    item\value_type: ezlocation
        api:
            ezcontent:
                template: "@NetgenEzPublishBlockManager/api/item/ezcontent.html.twig"
                match:
                    item\value_type: ezcontent
            ezlocation:
                template: "@NetgenEzPublishBlockManager/api/item/ezlocation.html.twig"
                match:
                    item\value_type: ezlocation
