view:
    rule_condition_view:
        value:
            ibexa_site_access:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/condition/value/ibexa_site_access.html.twig"
                match:
                    rule_condition\type: ibexa_site_access
            ibexa_site_access_group:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/condition/value/ibexa_site_access_group.html.twig"
                match:
                    rule_condition\type: ibexa_site_access_group
            ibexa_content_type:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/condition/value/ibexa_content_type.html.twig"
                match:
                    rule_condition\type: ibexa_content_type
