view:
    rule_target_view:
        value:
            ibexa_children:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/target/value/ibexa_children.html.twig"
                match:
                    rule_target\type: ibexa_children
            ibexa_content:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/target/value/ibexa_content.html.twig"
                match:
                    rule_target\type: ibexa_content
            ibexa_location:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/target/value/ibexa_location.html.twig"
                match:
                    rule_target\type: ibexa_location
            ibexa_subtree:
                template: "@NetgenLayoutsIbexa/admin/layout_resolver/target/value/ibexa_subtree.html.twig"
                match:
                    rule_target\type: ibexa_subtree
