view:
    rule_target_view:
        value:
            ez_children:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ez_children.html.twig"
                match:
                    rule_target\type: ez_children
            ez_content:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ez_content.html.twig"
                match:
                    rule_target\type: ez_content
            ez_location:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ez_location.html.twig"
                match:
                    rule_target\type: ez_location
            ez_subtree:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ez_subtree.html.twig"
                match:
                    rule_target\type: ez_subtree
