view:
    rule_target_view:
        value:
            ezchildren:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ezchildren.html.twig"
                match:
                    rule_target\type: ezchildren
            ezcontent:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ezcontent.html.twig"
                match:
                    rule_target\type: ezcontent
            ezlocation:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ezlocation.html.twig"
                match:
                    rule_target\type: ezlocation
            ezsubtree:
                template: "@NetgenLayoutsEzPlatform/admin/layout_resolver/target/value/ezsubtree.html.twig"
                match:
                    rule_target\type: ezsubtree
