parameters:
    netgen_block_manager.layout.resolver.condition_type.siteaccess.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\ConditionType\SiteAccess

services:
    netgen_block_manager.layout.resolver.condition_type.siteaccess:
        class: "%netgen_block_manager.layout.resolver.condition_type.siteaccess.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }
