parameters:
    netgen_block_manager.layout.resolver.condition_type.ezsiteaccess.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\ConditionType\SiteAccess

services:
    netgen_block_manager.layout.resolver.condition_type.ezsiteaccess:
        class: "%netgen_block_manager.layout.resolver.condition_type.ezsiteaccess.class%"
        arguments:
            - "%ezpublish.siteaccess.list%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }
