parameters:
    netgen_block_manager.layout.resolver.condition_matcher.siteaccess.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\ConditionMatcher\Matcher\SiteAccess

services:
    netgen_block_manager.layout.resolver.condition_matcher.siteaccess:
        class: "%netgen_block_manager.layout.resolver.condition_matcher.siteaccess.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_matcher }
