parameters:
    netgen_block_manager.layout.resolver.condition_type.ez_site_access.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\ConditionType\SiteAccess
    netgen_block_manager.layout.resolver.condition_type.ez_content_type.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\ConditionType\ContentType

services:
    netgen_block_manager.layout.resolver.condition_type.ez_site_access:
        class: "%netgen_block_manager.layout.resolver.condition_type.ez_site_access.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type, priority: 21 }

    netgen_block_manager.layout.resolver.condition_type.ez_content_type:
        class: "%netgen_block_manager.layout.resolver.condition_type.ez_content_type.class%"
        arguments:
            - "@ezpublish.api.service.content"
            - "@ezpublish.api.service.content_type"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type, priority: 20 }
