parameters:
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.location.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Location
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.content.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Content
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.children.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Children
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.subtree.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Subtree
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\SemanticPathInfo
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info_prefix.class: Netgen\Bundle\EzPublishBlockManagerBundle\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\SemanticPathInfoPrefix

services:
    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.location:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.location.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: location }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.content:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.content.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: content }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.children:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.children.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: children }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.subtree:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.subtree.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: subtree }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: semantic_path_info }

    netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info_prefix:
        class: "%netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler.semantic_path_info_prefix.class%"
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, identifier: semantic_path_info_prefix }
