parameters:
    netgen_block_manager.layout.resolver.target_value_provider.location.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\TargetValueProvider\Location
    netgen_block_manager.layout.resolver.target_value_provider.content.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\TargetValueProvider\Content
    netgen_block_manager.layout.resolver.target_value_provider.children.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\TargetValueProvider\Children
    netgen_block_manager.layout.resolver.target_value_provider.subtree.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\TargetValueProvider\Subtree
    netgen_block_manager.layout.resolver.target_value_provider.semantic_path_info.class: Netgen\Bundle\EzPublishBlockManagerBundle\Layout\Resolver\TargetValueProvider\SemanticPathInfo

services:
    netgen_block_manager.layout.resolver.target_value_provider.location:
        class: "%netgen_block_manager.layout.resolver.target_value_provider.location.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: location }

    netgen_block_manager.layout.resolver.target_value_provider.content:
        class: "%netgen_block_manager.layout.resolver.target_value_provider.content.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: content }

    netgen_block_manager.layout.resolver.target_value_provider.children:
        class: "%netgen_block_manager.layout.resolver.target_value_provider.children.class%"
        arguments:
            - "@ezpublish.api.service.location"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: children }

    netgen_block_manager.layout.resolver.target_value_provider.subtree:
        class: "%netgen_block_manager.layout.resolver.target_value_provider.subtree.class%"
        arguments:
            - "@ezpublish.api.service.location"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: subtree }

    netgen_block_manager.layout.resolver.target_value_provider.semantic_path_info:
        class: "%netgen_block_manager.layout.resolver.target_value_provider.semantic_path_info.class%"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: semantic_path_info }
            - { name: netgen_block_manager.layout.resolver.target_value_provider, identifier: semantic_path_info_prefix }
