parameters:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Location
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.content.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Content
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.children.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Children
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.subtree.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Subtree
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\SemanticPathInfo
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info_prefix.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\SemanticPathInfoPrefix

services:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: location }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.content:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.content.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: content }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.children:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.children.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: children }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.subtree:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.subtree.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: subtree }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: semantic_path_info }

    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info_prefix:
        class: "%netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.semantic_path_info_prefix.class%"
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler, alias: semantic_path_info_prefix }
