parameters:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location.class: Netgen\Bundle\EzPublishBlockManagerBundle\LayoutResolver\RuleHandler\Doctrine\TargetHandler\Location

services:
    netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location:
        class: %netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler.location.class%
        tags:
            - { name: netgen_block_manager.layout_resolver.rule_handler.doctrine.target_handler }
