block_definitions:
    ezcontent_field:
        name: 'eZ content field'
        view_types:
            ezcontent_field:
                name: 'eZ content field'

    ezcomponent:
        name: 'eZ component'
        icon: '/bundles/layoutsezplatform/images/icon-component-generic.svg'
        config_provider: ezplatform
        view_types:
            standard:
                name: 'Standard'
