parameters:
    netgen_block_manager.app.ezplatform.item_preview_template: '@@NetgenLayoutsEzPlatform/api/item/ngbm_app_preview.html.twig'
    netgen_block_manager.ezplatform.admin.pagelayout: '@@NetgenLayoutsEzPlatform/admin/pagelayout.html.twig'
