parameters:
    netgen_layouts.app.ezplatform.item_preview_template: '@@NetgenLayoutsEzPlatform/api/item/nglayouts_app_preview.html.twig'
    netgen_layouts.ezplatform.admin.pagelayout: '@@NetgenLayoutsEzPlatform/admin/pagelayout.html.twig'
