parameters:
    netgen_layouts.app.ezplatform.item_preview_template: '@@NetgenLayoutsEzPlatform/app/item/nglayouts_app_preview.html.twig'
    netgen_layouts.ezplatform.admin.pagelayout: '@@NetgenLayoutsEzPlatform/admin/pagelayout.html.twig'

    netgen_layouts.default.ezcomponent.parent_locations:
        ng_banner: 43
    # netgen_layouts.default.ezcomponent.parent_locations: []
    netgen_layouts.default.ezcomponent.default_parent_location: 2
