parameters:
    netgen_block_manager.app.ezplatform.item_preview_template: '@@NetgenEzPublishBlockManager/api/item/ngbm_app_preview.html.twig'
    netgen_block_manager.ezplatform.admin.pagelayout: '@@NetgenEzPublishBlockManager/admin/pagelayout.html.twig'
