nglayouts_ibexa_admin_location_layouts:
    path: /nglayouts/ibexa/admin/layouts/{locationId}
    controller: netgen_layouts.ibexa.admin.controller.location_layouts
    methods:  [GET]
    requirements:
        locationId: \d+

nglayouts_ibexa_admin_layout_wizard:
    path: /nglayouts/ibexa/admin/layouts/{locationId}/wizard
    controller: netgen_layouts.ibexa.admin.controller.layout_wizard
    methods:  [GET, POST]

nglayouts_ibexa_admin_layout_wizard_callback:
    path: /nglayouts/ibexa/admin/layouts/{locationId}/wizard/callback
    controller: netgen_layouts.ibexa.admin.controller.layout_wizard_callback
    methods:  [GET]

nglayouts_ibexa_admin_create_content:
    path: /nglayouts/ibexa/admin/layouts/content/create/{contentTypeIdentifier}/{languageCode}/{parentLocationId}
    controller: netgen_layouts.ibexa.admin.controller.create_content
    methods:  [GET]

nglayouts_ibexa_admin_delete_rule:
    path: /nglayouts/ibexa/admin/layouts/rules/{ruleId}/delete
    controller: netgen_layouts.ibexa.admin.controller.delete_rule
    methods:  [DELETE]
    defaults:
        _nglayouts_status: published
