nglayouts_ezadmin_location_layouts:
    path: /nglayouts/ezadmin/layouts/{locationId}
    controller: netgen_layouts.ezplatform.admin.controller.location_layouts
    methods:  [GET]
    requirements:
        locationId: \d+

nglayouts_ezadmin_layout_wizard:
    path: /nglayouts/ezadmin/layouts/{locationId}/wizard
    controller: netgen_layouts.ezplatform.admin.controller.layout_wizard
    methods:  [GET, POST]

nglayouts_ezadmin_layout_wizard_callback:
    path: /nglayouts/ezadmin/layouts/{locationId}/wizard/callback
    controller: netgen_layouts.ezplatform.admin.controller.layout_wizard_callback
    methods:  [GET]

nglayouts_ezadmin_create_content:
    path: /nglayouts/ezadmin/blocks/{blockId}/create-content/{contentTypeIdentifier}/{languageCode}/{parentLocationId}
    controller: netgen_layouts.ezplatform.admin.controller.create_content
    methods:  [GET]

nglayouts_ezadmin_delete_rule:
    path: /nglayouts/ezadmin/layouts/rules/{ruleId}/delete
    controller: netgen_layouts.ezplatform.admin.controller.delete_rule
    methods:  [DELETE]
    defaults:
        _nglayouts_status: published
