system:
    default:
        image_variations:
            ngbm_app_preview:
                reference: original
                filters:
                    - { name: thumbnail, params: { size: [80, 45], mode: outbound } }
                    - { name: strip }
