parameters:
    netgen_block_manager.collection.query_type.handler.ezcontent_search.class: Netgen\BlockManager\Ez\Collection\QueryType\Handler\ContentSearchHandler

services:
    netgen_block_manager.collection.query_type.handler.ezcontent_search:
        class: "%netgen_block_manager.collection.query_type.handler.ezcontent_search.class%"
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.search"
            - "@netgen_block_manager.ezpublish.content_provider"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_block_manager.collection.query_type_handler, type: ezcontent_search }
