services:
    netgen_layouts.ezplatform.collection.query_type_handler.content_search:
        class: Netgen\Layouts\Ez\Collection\QueryType\Handler\ContentSearchHandler
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_layouts.ezplatform.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.spi.persistence.section_handler"
            - "@ezpublish.spi.persistence.object_state_handler"
            - "@netgen_layouts.ezplatform.content_provider"
            - "@ezpublish.config.resolver"
        tags:
            - { name: netgen_layouts.query_type_handler, type: ezcontent_search }
