services:
    netgen_block_manager.collection.query_type.handler.ezcontent_search:
        class: Netgen\BlockManager\Ez\Collection\QueryType\Handler\ContentSearchHandler
        public: false
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_block_manager.ezpublish.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.spi.persistence.section_handler"
            - "@ezpublish.spi.persistence.object_state_handler"
            - "@netgen_block_manager.ezpublish.content_provider"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_block_manager.collection.query_type_handler, type: ezcontent_search }
